#%RAML 1.0
title: p-customer




/create:
  post:
    body:
      application/json:
        description: create a simple customer
    responses:
      201:
        body:
          application/json:
            